-- Extend app_themes with complete design token system
-- Run this in Supabase SQL Editor

ALTER TABLE public.app_themes
  ADD COLUMN IF NOT EXISTS secondary_color TEXT NOT NULL DEFAULT '#93BFC7',
  ADD COLUMN IF NOT EXISTS text_secondary_color TEXT NOT NULL DEFAULT '#4A5568',
  ADD COLUMN IF NOT EXISTS text_muted_color TEXT NOT NULL DEFAULT '#94A3B8',
  ADD COLUMN IF NOT EXISTS border_color TEXT NOT NULL DEFAULT '#E2E8F0',
  ADD COLUMN IF NOT EXISTS border_strong_color TEXT NOT NULL DEFAULT '#93BFC7',
  ADD COLUMN IF NOT EXISTS success_color TEXT NOT NULL DEFAULT '#4ADE80',
  ADD COLUMN IF NOT EXISTS warning_color TEXT NOT NULL DEFAULT '#FBBF24',
  ADD COLUMN IF NOT EXISTS danger_color TEXT NOT NULL DEFAULT '#F87171',
  ADD COLUMN IF NOT EXISTS info_color TEXT NOT NULL DEFAULT '#7FAED8',
  ADD COLUMN IF NOT EXISTS card_background TEXT NOT NULL DEFAULT '#FFFFFF',
  ADD COLUMN IF NOT EXISTS modal_background TEXT NOT NULL DEFAULT '#FFFFFF',
  ADD COLUMN IF NOT EXISTS sidebar_background TEXT NOT NULL DEFAULT '#FFFFFF',
  ADD COLUMN IF NOT EXISTS header_background TEXT NOT NULL DEFAULT '#FFFFFF',
  ADD COLUMN IF NOT EXISTS surface_elevated TEXT NOT NULL DEFAULT '#F8FAFC',
  ADD COLUMN IF NOT EXISTS button_primary TEXT NOT NULL DEFAULT '#ABE7B2',
  ADD COLUMN IF NOT EXISTS button_primary_hover TEXT NOT NULL DEFAULT '#CBF3BB',
  ADD COLUMN IF NOT EXISTS button_secondary TEXT NOT NULL DEFAULT 'transparent',
  ADD COLUMN IF NOT EXISTS button_secondary_hover TEXT NOT NULL DEFAULT '#E2E8F0',
  ADD COLUMN IF NOT EXISTS hover_background TEXT NOT NULL DEFAULT '#F1F5F9',
  ADD COLUMN IF NOT EXISTS selected_background TEXT NOT NULL DEFAULT '#E2E8F0',
  ADD COLUMN IF NOT EXISTS shadow_color TEXT NOT NULL DEFAULT 'rgba(0,0,0,0.08)',
  ADD COLUMN IF NOT EXISTS card_style TEXT NOT NULL DEFAULT 'elevated',
  ADD COLUMN IF NOT EXISTS border_style TEXT NOT NULL DEFAULT 'rounded',
  ADD COLUMN IF NOT EXISTS density TEXT NOT NULL DEFAULT 'normal';
